package nlp4s.english.std

import nlp4s.english.Lexicon
import nlp4s.english.lexicon.Direction
import nlp4s.english.lexicon.Preposition

trait StandardPrepositions { self: Lexicon.Builder =>
  addEntries(List(
    Preposition("under"),
    Preposition("next_to"),
    Preposition("on_top_of"),
    Preposition("into"),
    Preposition("among"),
    Preposition("opposite"),
    Preposition("around"),

    Preposition("at"),
    Preposition("in"),
    Preposition("on"),

    Preposition("along"),
    Preposition("across"),
    Preposition("behind"),
    Preposition("within"),
    Preposition("outside"),

    Preposition("aboard"),
    Preposition("about"),
    Preposition("above"),
    Preposition("after"),
    Preposition("against"),
    Preposition("amid"),
    Preposition("among"),
    Preposition("anti"),
    Preposition("as"),
    Preposition("before"),
    Preposition("below"),
    Preposition("beneath"),
    Preposition("beside"),
    Preposition("between"),
    Preposition("beyond"),
    Preposition("but"),
    Preposition("by"),
    Preposition("concerning"),
    Preposition("considering"),
    Preposition("despite"),
    Preposition("down"),
    Preposition("during"),
    Preposition("except"),
    Preposition("excluding"),
    Preposition("following"),
    Preposition("for"),
    Preposition("from"),
    Preposition("in"),
    Preposition("inside"),
    Preposition("like"),
    Preposition("minus"),
    Preposition("near"),
    Preposition("of"),
    Preposition("off"),
    Preposition("onto"),
    Preposition("opposite"),
    Preposition("outside"),
    Preposition("over"),
    Preposition("past"),
    Preposition("per"),
    Preposition("plus"),
    Preposition("regarding"),
    Preposition("round"),
    Preposition("save"),
    Preposition("since"),
    Preposition("than"),
    Preposition("through"),
    Preposition("to"),
    Preposition("toward"),
    Preposition("towards"),
    Preposition("underneath"),
    Preposition("unlike"),
    Preposition("until"),
    Preposition("up"),
    Preposition("upon"),
    Preposition("versus"),
    Preposition("via"),
    Preposition("with"),
    Preposition("within"),
    Preposition("without"),

    Direction("north"),
    Direction("south"),
    Direction("east"),
    Direction("west"),
    Direction("up"),
    Direction("down"),
    Direction("left"),
    Direction("right"),
    Direction("forward"),
    Direction("forwards"),
    Direction("backward"),
    Direction("backwards"),
    Direction("around"),
    ))
}
