package nlp4s.english.std

import nlp4s.english.Lexicon
import nlp4s.english.lexicon._

trait StandardAdjectives { self: Lexicon.Builder =>
  addEntries(List(
    Adjective("big", "bigger", "biggest"),
    Adjective("tall", "taller", "tallest"),
    Adjective("warm", "warmer", "warmest"),
    Adjective("cold", "colder", "coldest"),
    Adjective("light", "lighter", "lightest"),
    Adjective("quick", "quicker", "quickest"),
    Adjective("slow", "slower", "slowest"),
    SimpleAdjective("burnt"),
    SimpleAdjective("depressed"),
    SimpleAdjective("surprised"),
    SimpleAdjective("misunderstood"),
    SimpleAdjective("annoying"),
    SimpleAdjective("shocking"),
    SimpleAdjective("time_consuming"),
    SimpleAdjective("miserable"),
    SimpleAdjective("beautiful"),
    Adjective("witty", "wittier", "wittiest"),
    SimpleAdjective("wicked"),
    SimpleAdjective("confusing"),
    Adjective("rich", "richer", "richest"),
    Adjective("new", "newer", "newest"),
    Adjective("strange", "stranger", "strangest"),
    Adjective("rocky", "rockier", "rockiest"),
    SimpleAdjective("circular"),
    SimpleAdjective("helpful"),
    SimpleAdjective("competent "),
    Adjective("smelly", "smellier", "smelliest"),
    SimpleAdjective("stable"),
    SimpleAdjective("grumpy"),
    SimpleAdjective("devoted"),
    Adjective("smart", "smarter", "smartest"),
    SimpleAdjective("muscular"),
    SimpleAdjective("graceful"),
    Adjective("scary", "scarier", "scariest"),
    Adjective("safe", "safer", "safest"),
    SimpleAdjective("wooden"),
    Adjective("sleepy", "sleepier", "sleepiest"),
    Adjective("tardy", "tardier", "tardiest"),
    Adjective("hungry", "hungrier", "hungriest"),
    Adjective("strange", "stranger", "strangest"),
    SimpleAdjective("hopeful"),
    Adjective("proud", "prouder", "proudest"),
    Adjective("new", "newer", "newest"),
    SimpleAdjective("dainty"),
    SimpleAdjective("royal"),
    SimpleAdjective("arrogant"),
    Adjective("round", "rounder", "roundest"),
    SimpleAdjective("efficient"),
    SimpleAdjective("youthful"),
    SimpleAdjective("cumbersome"),
    SimpleAdjective("fickle"),
    Adjective("mild", "milder", "mildest"),
    SimpleAdjective("expensive"),
    Adjective("small", "smaller", "smallest"),
    Adjective("rude", "ruder", "rudest"),
    SimpleAdjective("generous"),
    SimpleAdjective("courageous"),
    Adjective("zany", "zanier", "zaniest"),
    Adjective("thin", "thinner", "thinnest"),
    SimpleAdjective("oval"),
    Adjective("dark", "darker", "darkest"),
    Adjective("hot", "hotter", "hottest"),
    SimpleAdjective("modern"),
    SimpleAdjective("petite"),
    SimpleAdjective("weary"),
    SimpleAdjective("adorable"),
    SimpleAdjective("adventurous"),
    SimpleAdjective("aggressive"),
    SimpleAdjective("agreeable"),
    SimpleAdjective("alert"),
    SimpleAdjective("alive"),
    SimpleAdjective("amused"),
    Adjective("angry", "angrier", "angriest"),
    SimpleAdjective("annoyed"),
    SimpleAdjective("annoying"),
    SimpleAdjective("anxious"),
    SimpleAdjective("arrogant"),
    SimpleAdjective("ashamed"),
    SimpleAdjective("attractive"),
    SimpleAdjective("average"),
    SimpleAdjective("awful"),
    Adjective("bad", "worse", "worst"),
    Adjective("good", "better", "best"),
    SimpleAdjective("bewildered"),
    SimpleAdjective("black"),
    SimpleAdjective("bloody"),
    SimpleAdjective("blue"),
    SimpleAdjective("blue_eyed"),
    SimpleAdjective("bored"),
    SimpleAdjective("brainy"),
    Adjective("brave", "braver", "bravest"),
    SimpleAdjective("breakable"),
    Adjective("bright", "brighter", "brightest"),
    Adjective("busy", "busier", "busiest"),
    Adjective("calm", "calmer", "calmest"),
    SimpleAdjective("careful"),
    SimpleAdjective("cautious"),
    SimpleAdjective("cheerful"),
    Adjective("clean", "cleaner", "cleanest"),
    Adjective("clear", "clearer", "clearest"),
    SimpleAdjective("clever"),
    SimpleAdjective("cloudy"),
    Adjective("clumsy", "clumsier", "clumsiest"),
    SimpleAdjective("colorful"),
    SimpleAdjective("combative"),
    SimpleAdjective("comfortable"),
    SimpleAdjective("concerned"),
    SimpleAdjective("condemned"),
    SimpleAdjective("confused"),
    SimpleAdjective("cooperative"),
    SimpleAdjective("courageous"),
    Adjective("crazy", "crasier", "crasiest"),
    Adjective("creepy", "creepier", "creepiest"),
    SimpleAdjective("crowded"),
    SimpleAdjective("cruel"),
    SimpleAdjective("curious"),
    Adjective("cute", "cuter", "cutest"),
    SimpleAdjective("dangerous"),
    Adjective("dark", "darker", "darkest"),
    SimpleAdjective("dead"),
    SimpleAdjective("defeated"),
    SimpleAdjective("defiant"),
    SimpleAdjective("delightful"),
    SimpleAdjective("depressed"),
    SimpleAdjective("determined"),
    SimpleAdjective("different"),
    SimpleAdjective("difficult"),
    SimpleAdjective("disgusted"),
    SimpleAdjective("distinct"),
    SimpleAdjective("disturbed"),
    SimpleAdjective("dizzy"),
    SimpleAdjective("doubtful"),
    SimpleAdjective("drab"),
    SimpleAdjective("dull"),
    Adjective("red", "redder", "reddest"),
  ))
}
