package nlp4s.english.std

import nlp4s.english.Lexicon
import nlp4s.english.lexicon._

trait StandardAdverbs { self: Lexicon.Builder =>
  addEntries(List(
    Adverb("lots"),
    Adverb("somewhat"),
    Adverb("barely"),
    Adverb("very"),
    Adverb("much"),
    Adverb("most"),
    Adverb("nearly"),
    Adverb("too"),
    Adverb("extremely"),
    Adverb("enough"),
    Adverb("so"),
    Adverb("slightly"),
    Adverb("especially", Some("special")),
    Adverb("just"),
    Adverb("almost"),
    Adverb("scarcely"),
    Adverb("virtually"),
    Adverb("fully"),
    Adverb("far"),
    Adverb("exceptionally"),
    Adverb("well", Some("good")),
    Adverb("fast"),
    Adverb("straight"),
    Adverb("hardly", Some("hardly")),
    Adverb("loudly"),
    Adverb("proudly"),
    Adverb("suspiciously"),
    Adverb("strangely"),
    Adverb("kindly"),
    Adverb("easily", Some("easy")),
    Adverb("rudely"),
    Adverb("neatly"),
    Adverb("quickly"),
    Adverb("slowly"),
    Adverb("generously"),
    Adverb("eagerly"),
    Adverb("accidentally"),
    Adverb("rapidly"),
    Adverb("hungrily", Some("hungry")),
    Adverb("foolishly"),
    Adverb("cheerfully"),
    Adverb("tomorrow"),
    Adverb("tonight"),
    Adverb("yesterday"),
    Adverb("now"),
    Adverb("then"),
    Adverb("today"),
    Adverb("already"),
    Adverb("daily"),
    Adverb("last"),
    Adverb("next"),
    Adverb("previously"),
    Adverb("after"),
    Adverb("afterwards"),
    Adverb("early"),
    Adverb("late"),
    Adverb("later"),
    Adverb("soon"),
    Adverb("since"),
    Adverb("still"),
    Adverb("just"),
    Adverb("seldom"),
    Adverb("always"),
    Adverb("usually"),
    Adverb("often"),
    Adverb("sometimes"),
    Adverb("rarely"),
    Adverb("never"),
    Adverb("ever"),
    Adverb("hardly_ever"),
    Adverb("occasionally"),
    Adverb("seldom"),
    Adverb("generally"),
    Adverb("frequently"),
    Adverb("normally"),
    Adverb("once"),
    Adverb("twice"),
    Adverb("thrice"),
    DegreeAdverb("very"),
    DegreeAdverb("more"),
    DegreeAdverb("most"),
    DegreeAdverb("mostly"),
    DegreeAdverb("somewhat"),
    DegreeAdverb("a_little"),
    DegreeAdverb("overwhelmingly"),
  ))
}

object StandardAdverbs {
  def degreeAdverbs = List(
    "lots",
    "somewhat",
    "bare",
    "very",
    "much",
    "most",
    "near",
    "too",
    "extreme",
    "enough",
    "so",
    "slight",
    "especial",
    "just",
    "almost",
    "scarce",
    "virtual",
    "full",
    "far",
    "exceptional",
    )

  def mannerAdverbs = List(
    "well",
    "fast",
    "straight",
    "hardly",
    "loud",
    "proud",
    "suspicious",
    "strange",
    "kind",
    "easy",
    "rude",
    "neat",
    "quick",
    "slow",
    "generous",
    "eager",
    "accidental",
    "rapid",
    "hungry",
    "foolish",
    "cheerful",
    )

  def timeAdverbs = List(
    "tomorrow",
    "tonight",
    "yesterday",
    "now",
    "then",
    "today",
    "already",
    "daily",
    "last",
    "next",
    "previously",
    "after",
    "afterwards",
    "early",
    "late",
    "later",
    "since",
    "still",
    "just",
    "seldom",
    "soon",
    )

  def frequencyAdverbs = List(
    "always",
    "usually",
    "often",
    "sometimes",
    "rarely",
    "never",
    "ever",
    "hardly_ever",
    "occasionally",
    "seldom",
    "generally",
    "frequently",
    "normally",
    "once",
    "twice",
    )
}
