package nlp4s.english

import nlp4s.base.Mode

case class TestCase(
  text: String,
  parses: Int,
  tokens: Int, // does not include "wall" token but includes concatenated tokens
  ignore: Boolean,
  mode: Mode,
)

object TestCase {
  val all: List[TestCase] =
    List(
      TestCase("move", 1, 1, false, Mode.Imperative),
      TestCase("the man runs", 1, 3, false, Mode.Declarative),
      TestCase("the man sees the table", 1, 5, false, Mode.Declarative),
      TestCase("the man picked up the table", 1, 5, false, Mode.Declarative),
      TestCase("pick up the table", 1, 3, false, Mode.Imperative),
      TestCase("pick up the mans leg", 1, 4, false, Mode.Imperative),
      TestCase("he drinks his beer", 1, 4, false, Mode.Declarative),
      TestCase("who drinks the beer", 1, 4, false, Mode.Interrogative),
      TestCase("who will drink the beer", 1, 5, false, Mode.Interrogative),
      TestCase("take the mans beer", 1, 4, false, Mode.Imperative),
      TestCase("the beer is mine", 1, 4, false, Mode.Declarative),
      TestCase("I move", 1, 2, false, Mode.Declarative),
      TestCase("he ran", 1, 2, false, Mode.Declarative),
      TestCase("they are looking", 1, 3, false, Mode.Declarative),
      TestCase("it is a table", 1, 4, false, Mode.Declarative),
      TestCase("she is walking", 1, 3, false, Mode.Declarative),
      TestCase("you pick up the table", 2, 4, false, Mode.Declarative),
      TestCase("he picks up my table", 1, 4, false, Mode.Declarative),
      TestCase("i pick up the table", 1, 4, false, Mode.Declarative),
      TestCase("tomorrow i pick up the table", 1, 5, false, Mode.Declarative),
      TestCase("i pick up the table tomorrow", 1, 5, false, Mode.Declarative),
      TestCase("she picked up the table", 1, 4, false, Mode.Declarative),
      TestCase("we are picking up the table", 1, 5, false, Mode.Declarative),
      TestCase("i am drinking", 1, 3, false, Mode.Declarative),
      TestCase("I am drinking the beer", 1, 5, false, Mode.Declarative),
      TestCase("I see the running man", 1, 5, false, Mode.Declarative),
      TestCase("I see the man drinking the beer", 1, 7, false, Mode.Declarative),
      TestCase("I see the men running", 1, 5, false, Mode.Declarative),
      TestCase("i was drinking", 1, 3, false, Mode.Declarative),
      TestCase("I drank it myself", 1, 4, false, Mode.Declarative),
      TestCase("he is himself", 1, 3, false, Mode.Declarative),
      TestCase("they pick up themselves", 1, 3, false, Mode.Declarative),
      TestCase("he run ran", 0, 3, false, Mode.Declarative),
      TestCase("he she it runs", 0, 4, false, Mode.Declarative),
      TestCase("we pick up the women", 1, 4, false, Mode.Declarative),
      TestCase("he will run to the table", 1, 6, false, Mode.Declarative),
      TestCase("he will be running", 1, 4, false, Mode.Declarative),
      TestCase("he must run", 1, 3, false, Mode.Declarative),
      TestCase("it shall drink the beer", 1, 5, false, Mode.Declarative),
      TestCase("he can't drink the beer", 1, 5, false, Mode.Declarative),
      TestCase("will he be taking the table", 1, 6, false, Mode.Interrogative),
      TestCase("will he run to the table", 1, 6, false, Mode.Interrogative),
      TestCase("he will ran to the table", 0, 6, false, Mode.Declarative),
      TestCase("he will runs to the table", 0, 6, false, Mode.Declarative),
      TestCase("he will running to the table", 0, 6, false, Mode.Declarative),
      TestCase("I am running", 1, 3, false, Mode.Declarative),
      TestCase("he is running to the table", 1, 6, false, Mode.Declarative),
      TestCase("is he running to the table", 1, 6, false, Mode.Interrogative),
      TestCase("the women drank", 1, 3, false, Mode.Declarative),
      TestCase("the women drinks", 0, 3, false, Mode.Declarative),
      TestCase("the quick man drinks the slow drink", 1, 7, false, Mode.Declarative),
      TestCase("the quick helpful man drinks the slow drink", 1, 8, false, Mode.Declarative),
      TestCase("the men walks over the road", 0, 6, false, Mode.Declarative),
      TestCase("the men run to the house", 1, 6, false, Mode.Declarative),
      TestCase("quickly drink the drink", 1, 4, false, Mode.Imperative),
      TestCase("drink the drink quickly", 1, 4, false, Mode.Imperative),
      TestCase("you picks up the table", 0, 4, false, Mode.Declarative),
      TestCase("who picks up the table", 1, 4, false, Mode.Interrogative),
      TestCase("who is picking up the table", 1, 5, false, Mode.Interrogative),
      TestCase("who pick up the table", 0, 4, false, Mode.Interrogative),
      TestCase("who runs", 1, 2, false, Mode.Interrogative),
      TestCase("who runs quickly", 1, 3, false, Mode.Interrogative),
      TestCase("what ran to the house", 1, 5, false, Mode.Interrogative),
      TestCase("who ran", 1, 2, false, Mode.Interrogative),
      TestCase("who is running", 1, 3, false, Mode.Interrogative),
      TestCase("who was running", 1, 3, false, Mode.Interrogative),
      TestCase("who was not running to the house", 1, 7, false, Mode.Interrogative),
      TestCase("who were not running", 0, 4, false, Mode.Interrogative),
      TestCase("who run", 0, 2, false, Mode.Interrogative),
      TestCase("are they a table", 1, 4, false, Mode.Interrogative),
      TestCase("Will I drink it", 1, 4, false, Mode.Interrogative),
      )
}


